spring:
  datasource:
    url: jdbc:postgresql://dpg-d5gn5ovpm1nc73ear35g-a.virginia-postgres.render.com:5432/energy_db_w855
    username: energy_db_w855_user
    password: GhI1GilQkIjNz4Z7uvMh7ZJ6JLcK2Efd
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  address: 0.0.0.0
